CREATE Table UhabCoapa.Usuario(Id_Usuario INT AUTO_INCREMENT NOT NULL, Nombre VARCHAR(55) NOT NULL,
ApellidoP VARCHAR(55) NOT NULL, ApellidoM VARCHAR(55) NOT NULL, Telefono VARCHAR(10) NOT NULL, 
Email VARCHAR(255) NOT NULL, Password VARCHAR(255) NOT NULL, Id_TUser INT NOT NULL, PRIMARY KEY(Id_Usuario))ENGINE = INNODB;